title: "school-site theme"
description: "A Jekyll theme"
author:
  name: "school-site"
  email: "mail@example.com"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 2
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-paginate

# Custom variables
google_analytics: ""
owner : "vellur"
year : "2018"
